* <<<PE101>>> C# AND .NET PROGRAMMING
:properties:
:author: S.Rajalakshmi & V.S. Felix Enigo
:end:

#+begin_comment
- 1. Reduced the content from AU 2017 syllabus (last 3 units)
- 2. Since the AU syllabus is vast, we have reduced some concepts to have indepth knowledge in basics. For changes, see the individual units.
- 3. No Corresponding course in M.E
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable
#+end_comment

#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO5            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    1 |    2 |    1 |
| Score          |    |  14 |  10 |   9 |   7 |   5 |   0 |   0 |   0 |   5 |    0 |    0 |    5 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn object oriented programming concepts in C#
- To write windows based applications and web applications using ADO.NET and ASP.NET
- To understand the basics of assemblies and .Net frameworks for communication and workflow.
  
{{{unit}}}
|UNIT I | C# LANGUAGE BASICS | 9 |
Introduction to .Net Architecture; Core C#: Variables -- Data Types --
Flow control-- Enumerations -- Namespaces -- Main method -- Comments ;
Objects and Types ; Inheritance; Generics; Arrays and Tuples;
Operators and Casts; Examples in C#.

{{{unit}}}
|UNIT II | C# ADVANCED FEATURES | 11 |
Delegates, Lambdas and Events; Strings and Regular Expressions;
Collections; Reflection; Errors and Exceptions; Manipulating Files:
Managing file system -- File operations.
#+begin_comment
Added: File concept
Removed: Memory Management and Pointers
Moved: Generics to Unit I
#+end_comment

{{{unit}}}
|UNIT III | WINDOWS BASED APPLICATIONS AND DATA HANDLING | 8 |
Core Windows Presentation Foundation (WPF): Geometry and
transformations -- Brushes -- Controls -- Layouts -- Styles and
Resources -- Triggers -- Templates; Core ADO .Net: Overview --
Database connections -- Commands -- Data reader -- Dataset class --
Data adapter; Case study: Library management system.

#+begin_comment
Modified: Unit III, IV, V from AU syllabus are modified and some concepts are removed
Added: Windows programming, WPF, and Data management as Unit III, 
ASP.Net web programming as Unit IV, Basics and WCF and WWF in Unit V
#+end_comment

{{{unit}}}
|UNIT IV | ASP .NET | 9 |
Core ASP .Net: .Net Framework for Web Applications -- Web Technologies
-- Handlers and Modules -- Global Application Class -- Request and
Response -- State Management; ASP .Net Web Forms: ASPX Page Model --
Master Pages -- Navigation -- Validating User input -- Accessing Data
-- Case study: E-commerce website development.

{{{unit}}}
|UNIT V | ASSEMBLIES, WCF AND WWF | 8 |
Assemblies: Application Domains -- Shared Assemblies -- Versioning;
Windows Communication Foundation (WCF) : Overview -- Creating a simple
service and client -- Contracts; Windows Workflow Foundation (WWF):
Overview -- Activities -- Workflows.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Apply object oriented and advanced concepts in program development using C# (K3)
- Develop windows based applications using C# in .NET framework using
  WPF (K3)
- Develop web applications using ASP.Net (K3)
- Develop database applications using ADO.Net (K3)
- Understand the basic concepts of Assemblies, WCF and WWF (K2).
 
** TEXT BOOK
1. Christian Nagel, Bill Evjen, Jay Glynn, Karli Watson, Morgan
   Skinner, ``Professional C# 2012 and .NET 4.5'', Wiley, 2012.

** REFERENCES
1. Ian Gariffiths, Mathew Adams, Jesse Liberty, ``Programming C#
   4.0'', O'Reilly, 4th Edition, 2010.
2. Andrew Troelsen, ``Pro C# 5.0 and the .NET 4.5 Framework'', Apress
   publication, 2012.
3. Andy Wigley, Daniel Moth, Peter Foot, ``Mobile Development
   Handbook'', Microsoft Press, 2011.
4. Harsh Bhasin, ``Programming in C#'', Oxford University Press, 2014.
5. Herbert Schildt, ``C# 4.0 The Complete Reference'', 1st Edition, Mc
   Graw Hill Education, 2010.

