* <<<PE303>>> SPEECH PROCESSING AND SYNTHESIS
:properties:
:author: Dr. B. Bharathi and Dr. P. Mirunalini
:date: 
:end:

#+startup: showall

#+begin_comment
- 1. First three unit contents are changed
- 2. For changes, see the individual units
- 3. Two text books and five reference books are included
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable.
#+end_comment

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO5            | K2 |   2 |   2 |   1 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| Score          |    |  13 |  10 |  8  |   0 |   5 |   0 |   0 |   5 |   5 |    5 |    0 |    5 |   8  |   13 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To explore the fundamentals of digital speech processing
- To understand the basic concepts and algorithms of speech processing
- To be familiar with the various speech signal representation, coding
  and recognition techniques
- To study the concepts and evaluation methods of speech synthesis.

{{{unit}}}
|UNIT I | FUNDAMENTALS OF DIGITAL SPEECH PROCESSING | 9 |
Introduction: Discrete-time signals and systems -- Transform
representation of signals and systems -- Fundamentals of digital
filters -- Sampling; Process of speech production -- Acoustic theory
of speech production -- Digital models for speech signals.
#+begin_comment
Added: Introduction: Discrete-time signals and systems -- Transform
representation of signals and systems -- Fundamentals of digital
filters -- Sampling.
Deleted :All the topics in the first unit is removed
Importance: Introduction about the discrete time signals is needed to study the speech signal processing.
#+end_comment

{{{unit}}}
|UNIT II | SPEECH SIGNAL ANALYSIS IN TIME DOMAIN| 9 |
Time-dependent processing of speech -- Methods for extracting the
Parameters: Energy -- Average magnitude -- Zero-crossing rate; Silence
discrimation using ZCR and energy -- Short-time autocorreleation
function -- Pitch period estimation using autocorrelation function.
#+begin_comment
Added: The full unit
Deleted: Except HMM, all the remaining topics are removed
Importance: Need to know the feature extraction in time domain
#+end_comment

{{{unit}}}
|UNIT III | SPEECH SIGNAL ANALYSIS IN FREQUENCY DOMAIN | 9 |
Short time fourier analysis -- Fourier transform and linear
interpretations -- Sampling rates -- Spectrographic displays --
Formant extraction -- Pitch extraction -- Linear predictive coding:
Autocorrelation method -- Covariance method; Solution of LPC equations
-- Durbin’s Recursive solution -- Application of LPC parameters --
Pitch detection.
#+begin_comment
Added: The full unit
Deleted: All the topics are removed 
Importance: Need to know the feature extraction in frequency domain
#+end_comment

{{{unit}}}
|UNIT IV | SPEECH RECOGNITION | 9 |
Introduction -- Preprocessing -- Parametric representation -- Speech
segmentation -- Dynamic time warping -- Vector quantization -- Hidden
Markov Model -- Language Models -- Developing an isolated digit
recognition system.
#+begin_comment
Added: Preprocessing -- Parametric representation -- Speech
segmentation -- Dynamic time warping -- Vector quantization -- Developing an isolated digit
recognition system.
Removed: discriminative training - speech recognition by humans
Importance: Steps for developing a speech recognition system are necessary
#+end_comment

{{{unit}}}
|UNIT V | SPEECH SYNTHESIS | 9 |
Attributes of speech synthesis -- Formant speech synthesis --
Concatenative speech synthesis -- Prosodic modification of speech --
Source filter models for prosody modification -- Evaluation of TTS
system.
#+begin_comment
Added: Prosodic modification of speech --
Source filter models for prosody modification
Changes: Speech synthesis is given as speech identification in AU2017 syllabus
Importance: Role of prosody in speech synthesis. 
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Illustrate how the speech production is modelled (K2)
- Extract features from the speech signal in time domain (K3)
- Analyze the speech signal in frequency domain (K3)
- Develop a speech recognition system using statistical approach (K3)
- Compare the various methods of speech synthesis (K2).
      
** TEXT BOOKS
1. L R Rabiner, R W Schafer, ``Digital Processing of Speech
   Signals'', Pearson Education, Delhi, India, 2004.
2. Xuedong Huang, Alex Acero, Hsiao-Wuen Hon, ``Spoken Language
   Processing -- A guide to Theory, Algorithm and System
   Development'', Prentice Hall PTR, 2001.

** REFERENCES
1. L R Rabiner, B H Jhuang, B Yegnanarayana, ``Fundamentals of
   Speech Recognition'', Pearson Education, 2009.
2. Thomas F Quatieri, ``Discrete-Time Speech Signal Processing'',
   Pearson Education, 2002.
3. Ben Gold, Nelson Morgan, ``Speech and Audio Signal Processing'',
   John Wiley and Sons Inc, 2004.
4. J R Deller Jr, J H L Hansen, J G Proakis, ``Discrete-Time
   Processing of Speech Signals'', Wiley-IEEE Press, NY, USA, 1999.
5. Daniel Jurafsky, James H Martin, ``Speech and Language
   Processing: An Introduction to Natural Language Processing,
   Computational Linguistics and Speech Recognition'', 2nd edition,
   Pearson education, 2013.
